services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:5000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      gunicorn --bind 0.0.0.0:5000
               --workers 4
               --log-level info
               --reload
               wsgi:app

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasksservice
    ports:
      - "5432:5432"

volumes:
  postgres_data:
